version: '3.9'

services:
  db:
    image: postgres:alpine
    # restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pg}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pg}
      POSTGRES_DB: ${POSTGRES_DB:-football}
    ports:
      - 5432:5432
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
  
  # server:
  #   build: .
  #   restart: always
  #   env_file:
  #     - .docker.env
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
volumes:
  postgres-data:
    driver: local