version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-football}
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - "mysql-data:/var/lib/mysql"
  # server:
  #   build: .
  #   restart: always
  #   env_file:
  #     - .docker.env
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
volumes:
  mysql-data:
    driver: local
